version: '3.8'

services:
  # 服务名称，你可以自定义，比如叫 web, api, app
  live-system-api-2.0:
    build: .              # 指定 Dockerfile 所在的目录，. 代表当前目录
    container_name: live-system-api-2.0  # 指定容器名称，方便管理
    restart: always       # 容器退出后自动重启，保证服务高可用
    #将当前目录 (.) 挂载到容器的 /app 目录
    volumes:
      - .:/app

    # 端口映射：宿主机端口:容器内端口
    ports:
      - "8084:8084"       # 如果你的 Python 应用运行在 8084 端口

# 定义数据卷
volumes:
  db-data: