server {
    listen 8080;
    server_name 859707243.xyz;

    # 设置请求体大小限制（如果有文件上传需求）
    client_max_body_size 20M;

    location / {
        # 这里的 fastapi 是 docker-compose 中定义的服务名称
        proxy_pass http://live-system-api-2.0:8000;

        # 以下配置用于正确转发请求头
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

}